import datetime

__sha__: str = ...
__sha_long__: str = ...
__build_time__: datetime.datetime = ...
__auto__: bool = ...

__all__ = (
    "__sha__",
    "__sha_long__",
    "__build_time__",
    "__auto__",
)
