import datetime

__auto__: bool = ...
__sha__: str = ...
__sha_short__: str = ...
__build_time__: datetime.datetime = ...

__all__ = (
    "__sha__",
    "__sha_short__",
    "__build_time__",
    "__auto__",
)
