[spanner]
token = "..."
debug_guilds = [982308600896704593]  # set to your server IDs, or omit for global commands.

[web]
host = "0.0.0.0"
port = 1237
base_url = "https://bots.nexy7574.co.uk/spanner/v3"  # the public facing URL of your API. can be omitted for automatic,
# However that's not recommended.
jwt_secret_key = "..."  # set to a random string. This is used to sign JWTs. You should keep this in a secure
# environment variable ($JWT_SECRET_KEY) though.
forwarded_allow_ips = "*"  # set to the IP address of your reverse proxy, or "*" to allow all.

[logging]
silence = ["discord.gateway"]

[cogs.meta]
support_guild_id = 729779146682793984  # set to the ID of your support server.
# OR you can set
support_guild_invite = "discord.gg/..." # set to the invite of your support server. Can actually be any arbitrary string
# so you *could* set it to a custom URL if you wanted.

[database]
uri = "sqlite://./database.db"  # set to your database URI. Can be postgres:// or sqlite://.
