[spanner]
token = "..."  # The bot's token
openai_token = "..."  # currently only used for moderation, which is free. Can be safely omitted.
debug_guilds = [982308600896704593]  # set to your server IDs, or omit for global commands.

[web]
enabled = true  # If `false`, the web server will still be initialised, but not started.
host = "0.0.0.0"
port = 1237
base_url = "https://bots.nexy7574.co.uk/spanner/v3"  # the public facing URL of your API. can be omitted for automatic,
# However that's not recommended.
root_path = "/api"  # if running behind an API with a subdirectory, set this to the prefix
# e.g.
# /api/* -> localhost:1237/ = root_path="/api"
# / -> localhost:3000
jwt_secret_key = "..."  # set to a random string. This is used to sign JWTs. You should keep this in a secure
# environment variable ($JWT_SECRET_KEY) though.
discord_client_secret = "..."  # set to your Discord client secret. This is used for OAuth2.
forwarded_allow_ips = "*"  # set to the IP address of your reverse proxy, or "*" to allow all.

[web.cors]
# See: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
allow_origins = [
    "https://bots.nexy7574.co.uk",
    "http://localhost:1237",
    "http://127.0.0.1:1237"
]  # set to your allowed origins. Can be "*" to allow all.
allow_credentials = true  # set to `true` to allow credentials (Authorization). Recommended.
allow_methods = ["GET", "POST", "PUT", "DELETE"]  # set to your allowed methods.
allow_headers = ["Authorization", "Content-Type"]  # set to your allowed headers.

[skus]
subscription_id = 0  # Set to the SKU ID of the subscription (type 5). This is used for premium.
key_id = 0  # Set for the SKU ID of the one-time key purchase. This is used for premium.

[logging]
silence = ["discord.gateway"]

[cogs.meta]
support_guild_id = 729779146682793984  # set to the ID of your support server.
# OR you can set
support_guild_invite = "discord.gg/..." # set to the invite of your support server. Can actually be any arbitrary string
# so you *could* set it to a custom URL if you wanted.

[database]
uri = "sqlite://./database.db"  # set to your database URI. Can be postgres:// or sqlite://.
